var StateAbbreviations =
{
	"alabama": "AL",
	"alaska": "AK",
	"arizona": "AZ",
	"arkansas": "AR",
	"california": "CA",
	"colorado": "CO",
	"connecticut": "CT",
	"delaware": "DE",
	"district of columbia": "DC",
	"florida": "FL",
	"georgia": "GA",
	"hawaii": "HI",
	"idaho": "ID",
	"illinois": "IL",
	"indiana": "IN",
	"iowa": "IA",
	"kansas": "KS",
	"kentucky": "KY",
	"louisiana": "LA",
	"maine": "ME",
	"maryland": "MD",
	"massachusetts": "MA",
	"michigan": "MI",
	"minnesota": "MN",
	"mississippi": "MS",
	"missouri": "MO",
	"montana": "MT",
	"nebraska": "NE",
	"nevada": "NV",
	"new hampshire": "NH",
	"new jersey": "NJ",
	"new mexico": "NM",
	"new york": "NY",
	"north carolina": "NC",
	"north dakota": "ND",
	"ohio": "OH",
	"oklahoma": "OK",
	"oregon": "OR",
	"pennsylvania": "PA",
	"rhode island": "RI",
	"south carolina": "SC",
	"south dakota": "SD",
	"tennessee": "TN",
	"texas": "TX",
	"utah": "UT",
	"vermont": "VT",
	"virginia": "VA",
	"washington": "WA",
	"west virginia": "WV",
	"wisconsin": "WI",
	"wyoming": "WY",

	"american samoa": "AS",
	"guam": "GU",
	"northern mariana islands": "MP",
	"puerto rico": "PR",
	"virgin islands": "VI",
	"us minor outlying islands": "UM",

	"alberta": "AB",
	"british columbia": "BC",
	"manitoba": "MB",
	"new brunswick": "NB",
	"newfoundland and labrador": "NL",
	"nova scotia": "NS",
	"northwest territories": "NT",
	"nunavut": "NU",
	"ontario": "ON",
	"prince edward island": "PE",
	"quebec": "QC",
	"saskatchewan": "SK",
	"yukon": "YT",

	"québec": "QC",
	"newfoundland": "NL",
	"labrador": "NL",
	"newfoundland & labrador": "NL",

	"fla": "FL",
	"tenn": "TN",
	"miss": "MS",
	"ala": "AL",
	"ill": "IL",
	"wis": "WI",
	"calif": "CA",
	"ark": "AR",
	"conn": "CT",
	"mass": "MA",
	"minn": "MN",
	"ind": "IN",
	"mich": "MI",
	"colo": "CO",
	"penn": "PA",
	"ariz": "AZ",
	"cali": "CA",
	"tex": "TX",
	"wash": "WA",
	"nev": "NV",

};

function getAbbr(full_name) {
	return StateAbbreviations[full_name.toLowerCase()] || full_name;
}
